src/Entity/Accounts.php
<?php

namespace App\Entity;

use App\Repository\AccountsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AccountsRepository::class)]
class Accounts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $surname;

    #[ORM\Column(type: 'string', length: 255)]
    private $email;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $description;

    #[ORM\Column(type: 'integer')]
    private $workplace;

    #[ORM\Column(type: 'text')]
    private $skill1;

    #[ORM\Column(type: 'text')]
    private $skill2;

    #[ORM\Column(type: 'boolean')]
    private $skill3;

    #[ORM\Column(type: 'boolean')]
    private $is_active;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getWorkplace(): ?int
    {
        return $this->workplace;
    }

    public function setWorkplace(int $workplace): self
    {
        $this->workplace = $workplace;

        return $this;
    }

    public function getSkill1(): ?string
    {
        return $this->skill1;
    }

    public function setSkill1(string $skill1): self
    {
        $this->skill1 = $skill1;

        return $this;
    }

    public function getSkill2(): ?string
    {
        return $this->skill2;
    }

    public function setSkill2(string $skill2): self
    {
        $this->skill2 = $skill2;

        return $this;
    }

    public function getSkill3(): ?bool
    {
        return $this->skill3;
    }

    public function setSkill3(bool $skill3): self
    {
        $this->skill3 = $skill3;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }
}

src/Controller/AdminPageController.php
<?php

namespace App\Controller;

use App\Entity\Accounts;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\NotBlank;

class AdminPageController extends AbstractController
{
    private $workplaces = [
        1 => "Tester",
        2 => "Developer",
        3 => "Project Manager"
    ];

    private $skills1 = [
        1 => "Systemy Testujące",
        2 => "Systemy Raportujące",
        3 => "Zna Selenium",
    ];

    private $skills2 = [
        1 => "Środowiska IDE",
        2 => "Języki programowania",
        3 => "Zna MySQL",
        ];

    private $skills3 = [
        1 => "Metodologie Prowadzenia Projektów",
        2 => "Systemy Raportujące",
        3 => "Zna Scrum",
    ];

    #[Route('/admin', name: 'app_admin_page')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $allAccounts = $doctrine->getRepository(Accounts::class);

        return $this->render('admin_page/index.html.twig', [
            'all' => $allAccounts->findBy(["is_active" => 1])
        ]);
    }

    #[Route('/admin/show/{id}', name: 'app_record_show', methods: "GET")]
    public function show($id, ManagerRegistry $doctrine): Response
    {
        $allAccounts = $doctrine->getRepository(Accounts::class);
        $record = $allAccounts->find($id);
        if (!$record) {
            return $this->redirectToRoute("app_admin_page");
        }
        return $this->render('admin_page/show.html.twig', [
            'record' => $record,
            'workplaces' => $this->workplaces,
            'skills' => [
                1 => $this->skills1,
                2 => $this->skills2,
                3 => $this->skills3
            ]
        ]);
    }

    #[Route('/admin/edit/{id}', name: 'app_record_edit')]
    public function edit($id, Request $request, ManagerRegistry $doctrine): Response
    {
        $allAccounts = $doctrine->getRepository(Accounts::class);
        $record = $allAccounts->find($id);
        $form = $this->buildForm($record);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $name = $form->getData()["first_name"];
            $surname = $form->getData()["surname"];
            $email = $form->getData()["email"];
            $desc = $form->getData()["desc"];
            $workplace = $form->getData()["workplace"];
            $skill1 = $skill2 = $skill3 = '';
            match ($workplace) {
                1 => [
                    $skill1 = $form->getData()["tester_skill1"],
                    $skill2 = $form->getData()["tester_skill2"],
                    $skill3 = $form->getData()["tester_skill3"],
                ],
                2 => [
                    $skill1 = $form->getData()["developer_skill1"],
                    $skill2 = $form->getData()["developer_skill2"],
                    $skill3 = $form->getData()["developer_skill3"],
                ],
                3 => [
                    $skill1 = $form->getData()["pm_skill1"],
                    $skill2 = $form->getData()["pm_skill2"],
                    $skill3 = $form->getData()["pm_skill3"],
                ],
            };
            $entityManager = $doctrine->getManager();
            $account = $entityManager->getRepository(Accounts::class)->find($id);
            $account->setFirstName($name);
            $account->setSurname($surname);
            $account->setEmail($email);
            $account->setDescription($desc);
            $account->setWorkplace($workplace);
            $account->setSkill1($skill1);
            $account->setSkill2($skill2);
            $account->setSkill3($skill3);
            $account->setIsActive(1);

            $entityManager->persist($account);
            $entityManager->flush();
            return $this->redirectToRoute("app_admin_page");
        }
        return $this->render('admin_page/edit.html.twig', [
            'form' => $form->createView(),
            'record' => $record,
            'workplaces' => $this->workplaces,
            'skills' => [
                1 => $this->skills1,
                2 => $this->skills2,
                3 => $this->skills3
            ]
        ]);
    }

    #[Route('/admin/delete/{id}', name: 'app_record_delete', methods: "GET")]
    public function delete($id, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
        $account = $entityManager->getRepository(Accounts::class)->find($id);
        $account->setIsActive(0);
        $entityManager->persist($account);
        $entityManager->flush();
        return $this->redirectToRoute("app_admin_page");
    }

    private function buildForm($record)
    {

        $form = $this->createFormBuilder()
            ->add('first_name', TextType::class, [
                'required' => true,
                'label' => 'Imię',
                'data' => $record->getFirstName(),
                'constraints' => [
                    new NotBlank(['message' => 'To pole jest wymagane']),
                ]
            ])
            ->add('surname', TextType::class, [
                'required' => true,
                'label' => 'Nazwisko',
                'data' => $record->getSurname(),
                'constraints' => [
                    new NotBlank(['message' => 'To pole jest wymagane']),
                ]
            ])
            ->add('email', EmailType::class, [
                'required' => true,
                'label' => 'E-mail',
                'data' => $record->getEmail(),
                'constraints' => [
                    new NotBlank(['message' => 'To pole jest wymagane']),
                    new Email(['message' => 'Wprowadzony adres e-mail nie jest poprawny']),
                ]
            ])
            ->add('desc', TextareaType::class, [
                'required' => false,
                'data' => $record->getDescription(),
                'label' => 'Opis'
            ])
            ->add('workplace', ChoiceType::class, [
                'required' => true,
                'label' => 'Stanowisko',
                'data' => $record->getWorkplace(),
                'choices'  => [
                    'wybierz' => 0,
                    'Tester' => 1,
                    'Developer' => 2,
                    'Project Manager' => 3,
                ]
            ])
            ->add('tester_skill1', TextType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 1 ? $record->getSkill1() : null,
                'label' => 'Systemy Testujące'
            ])
            ->add('tester_skill2', TextType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 1 ? $record->getSkill2() : null,
                'label' => 'Systemy Raportujące'
            ])
            ->add('tester_skill3', CheckboxType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 1 ? $record->getSkill3() : null,
                'label' => 'Tak'
            ])
            ->add('developer_skill1', TextType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 2 ? $record->getSkill1() : null,
                'label' => 'Środowiska IDE'
            ])
            ->add('developer_skill2', TextType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 2 ? $record->getSkill2() : null,
                'label' => 'Języki programowania'
            ])
            ->add('developer_skill3', CheckboxType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 2 ? $record->getSkill3() : null,
                'label' => 'Tak'
            ])
            ->add('pm_skill1', TextType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 3 ? $record->getSkill1() : null,
                'label' => 'Metodologie Prowadzenia Projektów'
            ])
            ->add('pm_skill2', TextType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 3 ? $record->getSkill2() : null,
                'label' => 'Systemy Raportowe'
            ])
            ->add('pm_skill3', CheckboxType::class, [
                'required' => false,
                'data' => $record->getWorkplace() === 3 ? $record->getSkill3() : null,
                'label' => 'Tak'
            ])
            ->add('save', SubmitType::class, [
                'label' => 'Wyślij',
            ])
            ->getForm();

        return $form;
    }
}

templates/admin_page/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<div class="container">

    <h2>Edycja</h2>
    {{ form_start(form, {'action': path("app_record_edit", {id: record.id}), 'method': 'POST', 'attr': {'class': 'bg-light border border-2'}}) }}
        <div class="form-group row">
            {{ form_label(form.first_name, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
            <div class="col-8">
                {{ form_widget(form.first_name, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row">
            {{ form_label(form.surname, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
            <div class="col-8">
                {{ form_widget(form.surname, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row">
            {{ form_label(form.email, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
            <div class="col-8">
                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row">
            {{ form_label(form.desc, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
            <div class="col-8">
                {{ form_widget(form.desc, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row">
            {{ form_label(form.workplace, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
            <div class="col-8">
                {{ form_widget(form.workplace, {'attr': {'class': 'form-select'}}) }}
            </div>
        </div>
        <div class="hidden-inputs-group" id="tester_group">
            <div class="form-group row">
                {{ form_label(form.tester_skill1, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
                <div class="col-8">
                    {{ form_widget(form.tester_skill1, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group row">
                {{ form_label(form.tester_skill2, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
                <div class="col-8">
                    {{ form_widget(form.tester_skill2, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-4">Zna Selenium</label>
                <div class="col-8">
                    <div class="custom-control custom-checkbox custom-control-inline">
                        {{ form_widget(form.tester_skill3, {'attr': {'class': 'custom-control-input'}}) }}
                        {{ form_label(form.tester_skill3, null, {'label_attr': {'class': 'custom-control-label'}}) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="hidden-inputs-group" id="developer_group">
            <div class="form-group row">
                {{ form_label(form.developer_skill1, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
                <div class="col-8">
                    {{ form_widget(form.developer_skill1, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group row">
                {{ form_label(form.developer_skill2, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
                <div class="col-8">
                    {{ form_widget(form.developer_skill2, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-4">Zna MySQL</label>
                <div class="col-8">
                    <div class="custom-control custom-checkbox custom-control-inline">
                        {{ form_widget(form.developer_skill3, {'attr': {'class': 'custom-control-input'}}) }}
                        {{ form_label(form.developer_skill3, null, {'label_attr': {'class': 'custom-control-label'}}) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="hidden-inputs-group" id="pm_group">
            <div class="form-group row">
                {{ form_label(form.pm_skill1, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
                <div class="col-8">
                    {{ form_widget(form.pm_skill1, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group row">
                {{ form_label(form.pm_skill2, null, {'label_attr': {'class': 'col-4 col-form-label'}}) }}
                <div class="col-8">
                    {{ form_widget(form.pm_skill2, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-4">Zna SCRUM</label>
                <div class="col-8">
                    <div class="custom-control custom-checkbox custom-control-inline">
                        {{ form_widget(form.pm_skill3, {'attr': {'class': 'custom-control-input'}}) }}
                        {{ form_label(form.pm_skill3, null, {'label_attr': {'class': 'custom-control-label'}}) }}
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-4 col-8">
                {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}
            </div>
        </div>

        {{ form_end(form) }}

</div>
{% endblock %}

templates/admin_page/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container">

        <h2>Wszystkie konta</h2>
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Imię</th>
                <th scope="col">E-mail</th>
                <th scope="col">Akcje</th>
            </tr>
            </thead>
            <tbody>
            {% for record in all %}
                <tr>
                    <td scope="row">{{ record.id }}</td>
                    <td>{{ record.firstName }}</td>
                    <td>{{ record.email }}</td>
                    <td>
                        <a href="{{ path("app_record_show", {id: record.id}) }}" class="btn btn-outline-info">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-lg" viewBox="0 0 16 16">
                                <path d="m9.708 6.075-3.024.379-.108.502.595.108c.387.093.464.232.38.619l-.975 4.577c-.255 1.183.14 1.74 1.067 1.74.72 0 1.554-.332 1.933-.789l.116-.549c-.263.232-.65.325-.905.325-.363 0-.494-.255-.402-.704l1.323-6.208Zm.091-2.755a1.32 1.32 0 1 1-2.64 0 1.32 1.32 0 0 1 2.64 0Z"/>
                            </svg>
                        </a>
                        <a href="{{ path("app_record_edit", {id: record.id}) }}" class="btn btn-outline-warning">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen" viewBox="0 0 16 16">
                                <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
                            </svg>
                        </a>
                        <a href="{{ path("app_record_delete", {id: record.id}) }}" class="btn btn-outline-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                            </svg>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/admin_page/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container d-grid gap-3">

        <h2>Podgląd</h2>
        <div class="row">
            <div class="col border border-secondary d-grid gap-3">
                <div class="row p-2 bg-light border">
                    <div class="col">
                        Imię
                    </div>
                    <div class="col">
                        {{ record.firstName }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        Nazwisko
                    </div>
                    <div class="col">
                        {{ record.surname }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        E-mail
                    </div>
                    <div class="col">
                        {{ record.email }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        Opis
                    </div>
                    <div class="col">
                        {{ record.description }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        Stanowisko
                    </div>
                    <div class="col">
                        {{ workplaces[record.workplace] }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        {{ skills[record.workplace][1] }}
                    </div>
                    <div class="col">
                        {{ record.skill1 }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        {{ skills[record.workplace][2] }}
                    </div>
                    <div class="col">
                        {{ record.skill2 }}
                    </div>
                </div>
                <div class="row p-2 bg-light border">
                    <div class="col">
                        {{ skills[record.workplace][3] }}
                    </div>
                    <div class="col">
                        {{ record.skill3 ? "Tak" : "Nie" }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}